Updater: Change color of string text to a readable one in dark theme
processhacker/processhacker pull request #1138
Opened 2022-02-23 10:49 UTC by TheEragon

I think this looks better, but feel free to change it to something else 😄 

![image](https://user-images.githubusercontent.com/5801389/155304961-fcd2b947-eca5-42af-9b65-837aa32bd3c6.png)

2022-02-23 12:45 UTC, Biswa96 commented
Just wondering. Is is possible to use GetSysColor? There are many hand written color values.

2022-03-01 06:39 UTC, dmex requested changes

2022-03-01 06:39 UTC, dmex commented on plugins/Updater/options.c
> +                                            if (!PhGetIntegerSetting(L"EnableThemeSupport"))
`If not` doesn't make sense. Use this instead:

```
if (PhGetIntegerSetting(L"EnableThemeSupport"))
    customDraw->clrText = RGB(125, 125, 125);
else
    customDraw->clrText = GetSysColor(COLOR_WINDOWTEXT);                           
                                                
```

2022-03-01 09:33 UTC, dmex approved these changes

2022-03-01 09:34 UTC, merged

2022-03-01 09:34 UTC, dmex commented
👍